(define (make-account balance password)
  (let ((incorrect-pw 0))
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incc-pw amount)
    (set! incorrect-pw (+ 1 incorrect-pw))
    (if (>= incorrect-pw 7)
        (begin call-the-cops "Cops called.")
       "Incorrect password"))
  (define (dispatch m pw)
    (if (eq? password pw)
        (begin (set! incorrect-pw 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request -- MAKE-ACCOUNT"
                                   m))))
        incc-pw))
  dispatch))
